config/routes.rb
Rails.application.routes.draw do

  get 'sro/show'
  get 'sro/create'
  
  get 'main/show_prof'
  get 'main/edit_prof'
  get 'main/cr_prof'

  get 'main/welcome'
  get 'main/index'
  
  get 'main/register'
  get 'main/login'
  get 'main/logout'
  
  post 'main/cr_acc'
  post 'main/create_profile'
  post 'main/action_login'
  post 'main/delete_prof'
  patch 'main/action_edit_prof'
  post 'main/edit_user_email'
  post 'main/edit_user_pass'
  
  delete 'sro/delete'
  post 'sro/step12'
  get 'sro/step2'
  patch 'sro/step23'
  get 'sro/step3'
  patch 'sro/step34'
  get 'sro/step4'
  patch 'sro/step45'
  get 'sro/step5'
  patch 'sro/step56'
  get 'sro/step6'
  patch 'sro/step67'
  get 'sro/step7'
  post 'sro/step78'
  get 'sro/step8'
  
  resources :people, :only => [:destroy, :create]

  root 'main#welcome'

end

app/controllers/main_controller.rb
# -*- encoding : utf-8 -*-
require 'digest/sha1'

class MainController < ApplicationController
  
  # filter ohranicenia pristupu pre prihlaseneho/neprihlaseneho
  before_filter :logged_in, :only => [:index, :show_prof, :edit_prof, :cr_prof, :del_prof, :logout]
  before_filter :not_logged, :only => [:welcome, :login, :register]
  
  def index
    # uvodna domovska stranka render
  end
  
  def welcome
    # uvodna stranka
  end
  
  def show_prof
    # zobrazenie profil
    @profile = Profile.find_by user_id: session[:user_id]
  end

  def edit_prof
    # stranka editacie profilu
    @profile = Profile.find_by user_id: session[:user_id]
  end

  def cr_prof
    # vytvaranie profilu
    @profile = Profile.new 
  end
  
  # vytvorenie profilu, post metoda
  def create_profile
    @profile = Profile.new(profile_params)
    @profile.user_id = session[:user_id]
    if @profile.save
      flash[:notice] = "Profil vytvorený."
      flash[:cr_prof]= "valid"
    else
      flash[:notice] = "Nevytvorený. Formulár nie je validný, prosím opravte chyby."
      flash[:cr_prof]= "invalid"
    end
    render "cr_prof"
  end

  # vymazanie profilu, post metoda
  def delete_prof
    profile = Profile.find_by user_id: session[:user_id]
    if profile.destroy
      flash[:notice] = "Profil vymazaný."
      flash[:edited]= "valid"
    end
    redirect_to(:action => 'show_prof')
  end
  
  #zmena profilu, patch metoda
  def action_edit_prof
    profile = Profile.find_by user_id: session[:user_id]
    if profile.update_attributes(profile_params)
      flash[:notice] = "Profil zmenený."
      flash[:edited]= "valid"
    else
      flash[:notice] = "Chyba formulára. Profil nezmenený."
      flash[:edited]= "invalid"
    end
    redirect_to(:action => 'show_prof')
  end

  # vyrenderovanie noveho pouzivatela, aj formular
  def register
    @user = User.new
  end
  
  # vytvorenie uzivatela, formularova post metoda
  def cr_acc
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Úspešne ste sa zaregistrovali."
      flash[:register]= "valid"
    else
      flash[:notice] = "Formulár nie je validný. Prosím opravte chyby na základe kontroly."
      flash[:register]= "invalid"
    end
    render "register"
  end
  
  # editovanie emailu pouzivatela, post metoda
  def edit_user_email
    user = User.find(session[:user_id])
    if user.update(email: params[:user][:email])
      flash[:notice] = "E-mail zmenený na " + params[:user][:email]
      flash[:edited]= "valid"
    else
      flash[:notice] = "Email nie je validný."
      flash[:edited]= "invalid"
    end
    redirect_to(:action => 'show_prof')
  end

  # editovanie hesla pouzivatela, post metoda
  def edit_user_pass
    user = User.find(session[:user_id])
    auth_user = User.auth(user.login,params[:user][:old_pass])
    if user.update(pass: params[:user][:pass]) && auth_user
      flash[:notice] = "Heslo zmenené."
      flash[:edited]= "valid"
    else
      flash[:notice] = "Nesprávne zadané heslo."
      flash[:edited]= "invalid"
    end
    redirect_to(:action => 'show_prof')
  end

  # renderovanie prihlasenia
  def login
    # formular prihlasenia
  end
  
  # prihlasenie, post metoda formulara
  def action_login
    auth_user = User.auth(params[:user_or_email],params[:prov_pass])
    if auth_user
      session[:user_id] = auth_user.id
      flash[:notice] = "Boli ste úspešne prihlásený ako #{auth_user.login}."
      flash[:logged]= "valid"
      redirect_to(:action => 'index')
    else
      flash[:notice] = "Nesprávne meno alebo heslo."
      flash[:logged]= "invalid"
      render "login"
    end
  end
  
  # odhlasenie
  def logout
    session[:user_id] = nil
    redirect_to(:action => 'welcome')
  end
  
  # zapuzdrenie parametrov, nepripustnost ziadnych inych, bezpecnostna polozka znama v Rails4
  private
  def user_params    
    params.require(:user).permit(:login, :pass, :pass_confirmation, :email)
  end
  def profile_params
    params.require(:profile).permit(:t_pred, :t_za, :meno, :priez, :ulica, :cislo, :obec, :psc, :stat)
  end
end

app/helpers/main_helper.rb
# -*- encoding : utf-8 -*-
module MainHelper
end

app/views/main/cr_prof.html.erb
<h1>Vytvor profil</h1>

 <% if flash[:cr_prof] == "valid" %>
  <span class="success_box"><%= flash[:notice] %></span>
 <% elsif flash[:cr_prof] == "invalid" %>
  <span class="error_box"><%= flash[:notice] %></span>
 <% end %>
  
<%= form_for(:profile, :url => {:controller => 'main', :action => 'create_profile'}) do |f| %>
  <p> Titul/y pred menom:<br/> <%= f.text_field :t_pred, :size => 10 %> </p>
  <p> Meno:<br/> <%= f.text_field :meno%> </p>
  <p> Priezvisko:<br/> <%= f.text_field :priez%> </p>
  <p> Titul/y za menom:<br/> <%= f.text_field :t_za, :size => 10 %> </p>
  <h4>Adresa</h4>
  <p> Ulica:<br/> <%= f.text_field :ulica, :size => 50 %> </p>
  <p> Súpisné číslo:<br/> <%= f.text_field :cislo, :size => 5 %> </p>
  <p> Obec:<br/> <%= f.text_field :obec, :size => 30 %> </p>
  <p> PSČ:<br/> <%= f.text_field :psc, :size => 5 %> </p>
  <p> Štát:<br/> <%= f.text_field :stat, :size => 30 %> </p>
    <%= f.submit :Vytvor %>
  <% end %>
  <% if @profile.errors.any? %>
    <ul>
    <% for message_error in @profile.errors.full_messages %>
      <li style="color:red"><%= message_error %></li>
    <% end %>
    </ul>
  <% end %>

app/views/main/edit_prof.html.erb
<h1>Zmena profilu</h1>

<%= form_for(@profile, :url => {:controller => 'main', :action => 'action_edit_prof'}) do |f| %>
  <p> Titul/y pred menom:<br/> <%= f.text_field :t_pred, :size => 10 %> </p>
  <p> Meno:<br/> <%= f.text_field :meno%> </p>
  <p> Priezvisko:<br/> <%= f.text_field :priez%> </p>
  <p> Titul/y za menom:<br/> <%= f.text_field :t_za, :size => 10 %> </p>
  <h4>Adresa</h4>
  <p> Ulica:<br/> <%= f.text_field :ulica, :size => 50 %> </p>
  <p> Súpisné číslo:<br/> <%= f.text_field :cislo, :size => 5 %> </p>
  <p> Obec:<br/> <%= f.text_field :obec, :size => 30 %> </p>
  <p> PSČ:<br/> <%= f.text_field :psc, :size => 5 %> </p>
  <p> Štát:<br/> <%= f.text_field :stat, :size => 30 %> </p>
  <% form_tag(main_action_edit_prof_path, method: "patch") %>
    <%= f.submit :Zmeň %>
<% end %>

app/views/main/index.html.erb
<% if flash[:logged] == "valid" %>
    <p><span class="success_box"><%= flash[:notice] %></span></p>
<% end %>

Vitajte v systéme Obchodného registra SR pre založenie spoločností.
Momentálne je k dispozícii alfa verzia 0.1.0, ktorá podporuje založenie spoločnosti s ručením obmedzeným.
V prípade akýchkoľvek otázok, prípadne stažností sa obrátte na systémových integrátorov.

app/views/main/login.html.erb
<h1>Prihlásenie</h1>

  <% if flash[:logged] == "invalid" %>
    <span class="error_box"><%= flash[:notice] %></span>
  <% end %>

<%= form_tag(:action => 'action_login') do %>
  <p>Používateľské meno alebo email:<br/> <%= text_field_tag(:user_or_email) %></p> 
  <p>Heslo:<br/> <%= password_field_tag :prov_pass %></p> 
  <%= submit_tag("Prihlásiť") %>
<% end %>

app/views/main/register.html.erb
<h1>Registrácia</h1>

  <% if flash[:register] == "valid" %>
    <span class="success_box"><%= flash[:notice] %></span>
  <% elsif flash[:register] == "invalid" %>
    <span class="error_box"><%= flash[:notice] %></span>
  <% end %>
  
  <div id="sidebar">
    <h3>Pomôcky:</h3>
    <ul>
      <li>minimálny počet znakov hesla je 6</li>
      <li>minimálny počet znakov používateľského mena je 3</li>
      <li>meno aj email musia byť unikátne</li>
    </ul>
  </div>
  
<%= form_for(:user, :url => {:controller => 'main', :action => 'cr_acc'}) do |f| %>
  <p> Užívateľské meno:<br/> <%= f.text_field :login%> </p>
  <p> Heslo:<br/> <%= f.password_field :pass%></p>
  <p> Heslo (potvrdenie):<br/> <%= f.password_field :pass_confirmation%> </p>
  <p> Email:<br/> <%= f.text_field :email%> </p>
    <%= f.submit :Registrácia %>
<% end %>
  <% if @user.errors.any? %>
    <ul>
    <% for message_error in @user.errors.full_messages %>
      <li style="color:red"><%= message_error %></li>
    <% end %>
    </ul>
  <% end %>

app/views/main/show_prof.html.erb
<h1>Fyzická osoba</h1>

<% if flash[:edited] == "valid" %>
  <span class="success_box"><%= flash[:notice] %></span>
<% elsif flash[:edited] == "invalid" %>
  <span class="error_box"><%= flash[:notice] %></span>
<% end %>

  <div id="sidebar">
    <h3>Informácia:</h3>
    Vyplnený profil bude použitý na autodopĺňanie osobných údajov a súčasne na identifikáciu navrhovateľa.    
  </div>

<% if @profile %>
  <p>
    <b>Meno a priezvisko: </b><br/>
    <%= @profile.t_pred + " " + @profile.meno + " " + @profile.priez + " " + @profile.t_za %>
  </p>
  <p>
    <b>Adresa:</b><br/>
    <%= @profile.ulica + "/ " + @profile.cislo.to_s %><br/>
    <%= @profile.psc.to_s + " " + @profile.obec %><br/>
    <%= @profile.stat %>
  </p>
  
  <%= link_to "Zmeniť profil", controller: "main", action: "edit_prof" %>
  <%= form_for(:user, :url => {:controller => 'main', :action => 'delete_prof'}) do |f| %>
    <%= f.submit :"Vymaž profil" %> 
  <% end %>
<% else %>
 <%= link_to "Vytvor profil", controller: "main", action: "cr_prof" %>
<% end %>

<h3>Nastavenia</h3>

  <b>Aktuálny e-mail:</b> <%= @logged_user.email %>
  <%= form_for(:user, :url => {:controller => 'main', :action => 'edit_user_email'}) do |f| %>
    Nastaviť nový email: <%= f.text_field :email%> &nbsp; <%= f.submit :"Zmeň email" %> 
  <% end %>
  <br/>
  <%= form_for(:user, :url => {:controller => 'main', :action => 'edit_user_pass'}) do |f| %>
    Staré heslo: <%= f.password_field :old_pass%><br/>
    Nové heslo: <%= f.password_field :pass%><br/>
    Nové znovu: <%= f.password_field :pass_confirmation%><br/>
    <%= f.submit :"Zmeň heslo" %> 
  <% end %>

app/views/main/welcome.html.erb
<h1>Vitajte</h1>
Tieto stránky sú v skúšobnej verzii. Slúžia občanom pre vytvorenie spoločnosti s ručením obmedzeným s dôrazom na elektronickú komunikáciu podľa platnej legislatívy.
<br/>
Pred používaním sa prihláste. Pokiaľ ešte nemáte účet, zaregistrujte sa.
  