config/routes.rb
Rails.application.routes.draw do

  get 'sro/show'
  get 'sro/create'
  
  get 'main/show_prof'
  get 'main/edit_prof'
  get 'main/cr_prof'

  get 'main/welcome'
  get 'main/index'
  
  get 'main/register'
  get 'main/login'
  get 'main/logout'
  
  post 'main/cr_acc'
  post 'main/create_profile'
  post 'main/action_login'
  post 'main/delete_prof'
  patch 'main/action_edit_prof'
  post 'main/edit_user_email'
  post 'main/edit_user_pass'
  
  delete 'sro/delete'
  post 'sro/step12'
  get 'sro/step2'
  patch 'sro/step23'
  get 'sro/step3'
  patch 'sro/step34'
  get 'sro/step4'
  patch 'sro/step45'
  get 'sro/step5'
  patch 'sro/step56'
  get 'sro/step6'
  patch 'sro/step67'
  get 'sro/step7'
  post 'sro/step78'
  get 'sro/step8'
  
  resources :people, :only => [:destroy, :create]

  root 'main#welcome'

end

app/models/person.rb
# -*- encoding : utf-8 -*-
class Person < ActiveRecord::Base
  
  PSC_RGXP = %r"[0-9]{6}/[0-9]{4}"
  
  validates :meno, :presence => true
  validates :priez, :presence => true
  validates :rc, :presence => true, :format => PSC_RGXP
  validates :ulica, :presence => true
  validates :cislo, :presence => true, :numericality => true
  validates :obec, :presence => true
  validates :psc, :presence => true, :numericality => true
  validates :stat, :presence => true
  validates :sposob, :presence => true
  validates :typ, :presence => true
  validates :vklad, :presence => true, :numericality => true
  validates :splatene, :presence => true, :numericality => true
  
end

app/controllers/people_controller.rb
# -*- encoding : utf-8 -*-
class PeopleController < ApplicationController
  
  # delete metoda, odpoveda len na javascript a javascriptom, AJAX
  def destroy
    @sro = Sro.find(params[:sro_id])
    @person = Person.find(params[:id])
    case @person.typ
      when 1
        @all_asso = @sro.people.where(:typ => 1)
      when 2
        @all_mdir = @sro.people.where(:typ => 2)
      when 3
        @all_sup = @sro.people.where(:typ => 2)
    end
    @person.destroy
    respond_to do |format|
      format.js
    end
  end

  # create metoda, podobna ako delete
  def create
    @sro = Sro.find(params[:person][:sro_id])
    case params[:person][:typ].to_i
      when 1
        @all_asso = @sro.people.where(:typ => 1)
      when 2
        @all_mdir = @sro.people.where(:typ => 2)
      when 3
        @all_sup = @sro.people.where(:typ => 2)
    end
    @person = Person.new(person_params)
    case params[:person][:typ].to_i
      when 1
        @person.typ = 1
      when 2
        @person.typ = 2
      when 3
        @person.typ = 3
    end
    @person.sro_id = @sro.id
    @person.funkcia_od = Time.now
    @person.save
    respond_to do |format|
      format.js
    end
  end
  
  def person_params
    params.require(:person).permit(:id, :ulica, :cislo, :obec, :psc, :stat, :t_pred, :meno, :priez, :t_za, :vklad, :splatene, :sro_id, :sposob, :rc, :dat_nar, :typ)
  end
  
end

app/views/people/_list.html.erb
<% if @all_asso %>
  <%@all_asso.each do |e|%>
   <p>
   <b>Meno:</b> <%= e.t_pred + " " + e.meno + " " +  e.priez + " " + e.t_za %> <br/>
   <b>Adresa:</b><br/>
   <%= e.ulica + "/ " + e.cislo.to_s %> <br/>
   <%= e.psc.to_s + ", " + e.obec %><br/>
   <%= e.stat %><br/>
   <b>Rodné číslo:</b> <%= e.rc %> <br/>
   <b>Vklad: <%= e.vklad %></b> EUR<br/>
   <b>Splatene: <%= e.splatene %></b> EUR<br/>
   <%= link_to "Odobrať", person_path(e, :sro_id => @sro.id), method: :delete, :remote => true %>
   </p>
  <%end%>
<% end%>

<% if @all_mdir %>
  <% @all_mdir.each do |e| %>
   <p>
   <b>Meno:</b> <%= e.t_pred + " " + e.meno + " " +  e.priez + " " + e.t_za %> <br/>
   <b>Adresa:</b><br/>
   <%= e.ulica + "/ " + e.cislo.to_s %> <br/>
   <%= e.psc.to_s + ", " + e.obec %><br/>
   <%= e.stat %><br/>
   <p> Dátum narodenia:<br/> <%= e.dat_nar %> </p>
   <p> Rodné číslo:<br/> <%= e.rc %> </p>
   <b>Spôsob konania:</b> <%= e.sposob %> </p>
   <%= link_to "Odobrať", person_path(e, :sro_id => @sro.id), method: :delete, :remote => true %>
   </p>
  <% end %>
<% end%>

<% if @all_sup %>
  <% @all_sup.each do |e| %>
   <p>
   <b>Meno:</b> <%= e.t_pred + " " + e.meno + " " +  e.priez + " " + e.t_za %> <br/>
   <b>Adresa:</b><br/>
   <%= e.ulica + "/ " + e.cislo.to_s %> <br/>
   <%= e.psc.to_s + ", " + e.obec %><br/>
   <%= e.stat %><br/>
   <p> Dátum narodenia:<br/> <%= e.dat_nar %> </p>
   <p> Rodné číslo:<br/> <%= e.rc %> </p>
   <%= link_to "Odobrať", person_path(e, :sro_id => @sro.id), method: :delete, :remote => true %>
   </p>
  <% end %>
<% end%>

<% if @person.errors.any? %>
    <ul>
    <% for message_error in @person.errors.full_messages %>
      <li style="color:red"><%= message_error %></li>
    <% end %>
    </ul>
 <%end %>

app/views/people/create.js.erb
$('.list').html("<%= escape_javascript(render('people/list')) %>");
$('input:text', $('#new_person')).each(function () {
    $(this).val("");
});

app/views/people/destroy.js.erb
$('.list').html("<%= escape_javascript(render('people/list')) %>");