config/routes.rb
Rails.application.routes.draw do

  get 'sro/show'
  get 'sro/create'
  
  get 'main/show_prof'
  get 'main/edit_prof'
  get 'main/cr_prof'

  get 'main/welcome'
  get 'main/index'
  
  get 'main/register'
  get 'main/login'
  get 'main/logout'
  
  post 'main/cr_acc'
  post 'main/create_profile'
  post 'main/action_login'
  post 'main/delete_prof'
  patch 'main/action_edit_prof'
  post 'main/edit_user_email'
  post 'main/edit_user_pass'
  
  delete 'sro/delete'
  post 'sro/step12'
  get 'sro/step2'
  patch 'sro/step23'
  get 'sro/step3'
  patch 'sro/step34'
  get 'sro/step4'
  patch 'sro/step45'
  get 'sro/step5'
  patch 'sro/step56'
  get 'sro/step6'
  patch 'sro/step67'
  get 'sro/step7'
  post 'sro/step78'
  get 'sro/step8'
  
  resources :people, :only => [:destroy, :create]

  root 'main#welcome'

end

app/models/sro.rb
# -*- encoding : utf-8 -*-
class Sro < ActiveRecord::Base
  
  has_many :opandsros
  has_many :operations, through: :opandsros
  has_many :people
  
  accepts_nested_attributes_for :operations

  validates :nazov, :presence => true, :uniqueness => true
  validates :ulica, :presence => true
  validates :cislo, :presence => true, :numericality => true
  validates :obec, :presence => true
  validates :psc, :presence => true, :numericality => true
  validates :stat, :presence => true
  validates :imanie, :numericality => {greater_than_or_equal_to: 5000, only_integer: true}, :on => :update
  validates :splatene, :numericality => {greater_than_or_equal_to: 2500, only_integer: true}, :on => :update
  
end

app/controllers/sro_controller.rb
# -*- encoding : utf-8 -*-
require 'uri'
class SroController < ApplicationController
  
  # ohranicenie pristupu
  before_filter :logged_in, :only => [:show, :create, :step2, :step3, :step4, :step5, :step6, :step7, :step8]
  
  # udaje pre volania back-endu
  USERNAME = "frontend"
  PASSWORD = "frontend"
  API_BASE_URL = "http://localhost:4567"
  
  # typy osob: 1 - spolocnik, 2 - konatel, 3 - clen dozornej rady
  # vsetky kroky su overovane na prave zadany step v objekte spolocnosti, aby sa nedali preskakovat
  
  def show
    # zoznam spolocnosti
    @sros = User.find(session[:user_id]).sros
  end
  
  # vytvorenie spolocnosti, render formular
  def create
    @sro = Sro.new
    @navrh = Profile.find_by user_id: session[:user_id]
    if !@navrh
      flash[:notice] = "Profil nevyplnený. Navrhovateľom je práve príhlásený používateľ."
      flash[:step1]= "invalid"
      redirect_to(:action => 'show')
    end
  end
  
  # action metoda ulozenia spolocnosti
  def step12
    @sro = Sro.new(sro_params)
    @sro.user_id = session[:user_id]
    @sro.forma = "sro"
    if !@sro.save
      flash[:notice] = "Chyba zadaných údajov"
      flash[:step1]= "invalid"
      @navrh = Profile.find_by user_id: session[:user_id]
      render "create"
    else
      redirect_to(:action => 'step2', :sro_id => @sro.id)
    end
  end
  
  # render cinnosti
  def step2
    begin
      @sro = Sro.find(params[:sro_id])
    rescue
      redirect_to(:action => 'show') and return
    end
    @all_operations = Operation.all
    @group = @sro.opandsros.build
  end
  
  # overenie cinnosti v backende, vytvorenie cinnosti ku spolocnosti
  def step23
    @sro = Sro.find(params[:sro][:id])
    @group = @sro.opandsros.build
    @all_operations = Operation.all
    @resps = []
    @next = true
    params[:sro][:operation_ids].delete_if(&:blank?)
    params[:sro][:operation_ids].each {|oid|
      o = Operation.find(oid)
      uri = "#{API_BASE_URL}/checkop/"+URI::encode(@sro.nazov+"/"+o.popis)
      rest_resource = RestClient::Resource.new(uri, USERNAME, PASSWORD)
      begin
        resp = rest_resource.get
      rescue
        flash[:notice] = "Vzdialená databáza ŽRSR nedostupná, skúste neskôr."
        flash[:status]= "invalid"
        render 'step2' and return
      end
      if resp.eql? "0"
        @next = false
        @resps << o.popis
      end
    }
    if @next
      @sro.update_attributes(:proces => "step3")
      redirect_to(:action => 'step3', :sro_id => @sro.id)
    else
      redirect_to(:action => 'step2', :sro_id => @sro.id, :resps => @resps)
    end
  end
  
  # pridavanie spolocnikov
  def step3
    begin
      @sro = Sro.find(params[:sro_id])
    rescue
      redirect_to(:action => 'show') and return
    end
    @person = Person.new
    @all_asso = Person.where(:typ => 1, :sro_id => @sro.id)
  end 
  
  # action metoda na overenie spolocnikov a ulozenie
  def step34
    @next = true
    # kontrola poctu spolocnikov
    @asso = Person.where(:typ => 1, :sro_id => params[:sro][:id])
    @asso.each {|a|
        uri = "#{API_BASE_URL}/checktax/"+a.rc.sub!('/','-')
        rest_resource = RestClient::Resource.new(uri, USERNAME, PASSWORD)
      begin
        resp = rest_resource.get
      rescue Errno::ECONNREFUSED, Errno::EHOSTUNREACH
        flash[:notice] = "Vzdialená databáza DÚSR pre overenie podlžnosti na dani nedostupná, skúste neskôr."
        flash[:status]= "invalid"
        redirect_to(:action => 'step3', :sro_id => params[:sro][:id]) and return
      end
      if resp.eql? "true"
        @next = false
      end
    }
    if @next
      if @asso.size == 1
        if Person.where(:typ => 1, :id => @asso.first).size > 2
          flash[:notice] = "Spoločník už je jediným spoločníkom v dvoch spoločnostiach s ručením obmedzeným."
          flash[:status]= "invalid"
          redirect_to(:action => 'step3', :sro_id => params[:sro][:id])
        else
          Sro.find(params[:sro][:id]).update_attributes(:proces => "step4")
          redirect_to(:action => 'step4', :sro_id => params[:sro][:id])
        end
      elsif @asso.size > 1
        Sro.find(params[:sro][:id]).update_attributes(:proces => "step4")
        redirect_to(:action => 'step4', :sro_id => params[:sro][:id])
      else
        flash[:notice] = "Minimálne jeden spoločník potrebný."
        flash[:status]= "invalid"
        redirect_to(:action => 'step3', :sro_id => params[:sro][:id])
      end
    else
      flash[:notice] = "Jeden alebo viac spoločníkov má daňové podlžnosti, prosím kontaktuje Daňový Úrad SR a pokračujte vo vytváraní po vyrovaní podlžností."
      flash[:status]= "invalid"
      redirect_to(:action => 'step3', :sro_id => params[:sro][:id])
    end
  end
    
  # pridavanie konatelov, formular
  def step4
    begin
      @sro = Sro.find(params[:sro_id])
    rescue
      redirect_to(:action => 'show') and return
    end
    @person = Person.new
    @all_mdir = Person.where(:typ => 2, :sro_id => @sro.id)  
  end
  
  # action metoda pre pridanie konatelov a overovanie
  def step45
    @mdir = Person.where(:typ => 2, :sro_id => params[:sro][:id])
    if @mdir.size < 1
      flash[:notice] = "Minimálne jeden konateľ potrebný."
      flash[:status]= "invalid"
      redirect_to(:action => 'step4', :sro_id => params[:sro][:id])
    else
      Sro.find(params[:sro][:id]).update_attributes(:proces => "step5")
      redirect_to(:action => 'step5', :sro_id => params[:sro][:id])
    end
  end
  
  # pridavanie dozornej rady
  def step5
    begin
      @sro = Sro.find(params[:sro_id])
    rescue
      redirect_to(:action => 'show') and return
    end
    @person = Person.new
    @all_sup = Person.where(:typ => 3, :sro_id => @sro.id)      
  end
  
  # action metoda pre pridanie a overenie dozornej rady
  def step56
    @sups = Person.where(:typ => 3, :sro_id => params[:sro][:id])
    if @sups.size < 3
      flash[:notice] = "Minimálne traja členovia dozornej rady potrební."
      flash[:status]= "invalid"
      redirect_to(:action => 'step5', :sro_id => params[:sro][:id])
    else
      Sro.find(params[:sro][:id]).update_attributes(:proces => "step6")
      redirect_to(:action => 'step6', :sro_id => params[:sro][:id])
    end    
  end
  
  # imanie, formular
  def step6
    begin
      @sro = Sro.find(params[:sro_id])
    rescue
      redirect_to(:action => 'show') and return
    end
  end
  
  # action metoda pre nastavenie imania a bankoveho spojenia, overenie backendom
  def step67
    @sro = Sro.find(params[:sro][:id])
    if params[:banka][:iban].empty? || params[:sro][:imanie].empty? || params[:sro][:splatene].empty?
      flash[:notice] = "Všetky polia musia byť vyplnené"
      flash[:status]= "invalid"
      render 'step6' and return
    end
    uri = "#{API_BASE_URL}/getStatus/"+params[:banka][:iban]
    rest_resource = RestClient::Resource.new(uri, USERNAME, PASSWORD)
    begin
      resp = rest_resource.get
    rescue
      flash[:notice] = "Vzdialená databáza banky momentálne nedostupná, skúste neskôr."
      flash[:status]= "invalid"
      render 'step6' and return
    end
    @sro.proces = "step7"
    # @sro.update_attributes(:proces => "step7")
    if @sro.update_attributes(sro_params)
      if resp.eql? params[:sro][:splatene]
        redirect_to(:action => 'step7', :sro_id => params[:sro][:id]) and return
      else
        flash[:notice] = "Stav účtu podľa aktuálnych bankových údajov nekorešponduje, prosím vyrovnajte stav účtu pred pokračovaním."
        flash[:status]= "invalid"
        render 'step6' and return
      end
    end
    render 'step6'
  end
  
  # pridanie dokumentov, formular
  def step7
    begin
      @sro = Sro.find(params[:sro_id])
    rescue
      redirect_to(:action => 'show') and return
    end
    @zip = Zip.new
  end
  
  # action metoda na pridavanie dokumentov
  def step78
    @sro = Sro.find(params[:sro][:id])
    if !params[:zip]
      flash[:notice] = "Nevybrali ste žiadny súbor"
      flash[:status]= "invalid"
      render 'step7' and return
    end
    @zip = Zip.new(zip_params)
    @zip.sro_id = params[:sro][:id]
    ziptmp = Zip.find_by sro_id: @sro.id
    if ziptmp
      ziptmp.destroy
    end
    if @zip.save
      @sro.update_attributes(:proces => "step8")
      redirect_to(:action => 'step8', :sro_id => @sro.id)
    else
      flash[:notice] = "Nastala chyba pri ukladaní dokumentu"
      flash[:status]= "invalid"
      render "step7"
    end
  end
  
  # posledny krok v ktorom proces konci a ocakava schvalenie
  def step8
    begin
      @sro = Sro.find(params[:sro_id])
    rescue
      redirect_to(:action => 'show') and return
    end
    @zip = Zip.find_by sro_id: params[:sro_id]
  end
    
  # aciton metoda na mazanie rozpracovanej spolocnosti
  def delete
    @sro = Sro.find(params[:sro_id])
    if @sro.destroy
      flash[:notice] = "Proces založenia vymazaný."
      flash[:deleted]= "valid"
    end
    redirect_to(:action => 'show')
  end

  # zapuzdrenie parametrov, zname v Rails4
  private
 
  def sro_params
    params.require(:sro).permit(:id, :ulica, :cislo, :obec, :psc, :stat, :nazov, :proces, :ico, :forma, :imanie, :splatene, :document, :user_id, operation_ids: [])
  end
  
  def person_params
    params.require(:person).permit(:id, :ulica, :cislo, :obec, :psc, :stat, :t_pred, :meno, :priez, :t_za, :vklad, :typ, :splatene, :sposob, :rc, :dat_nar)
  end
  
  def zip_params
    begin  
      params.require(:zip).permit(:id, :sro_id, :file)
    rescue
    end
  end
  
end

app/helpers/sro_helper.rb
# -*- encoding : utf-8 -*-
module SroHelper
  def print_status(sro)
    puts sro.schvalene
    if !sro.schvalene
      return "Očakáva schválenie (je možné upraviť kroky a odstrániť spoločnosť)"
    else
      return "Schválené, spoločnosť registrovaná"
    end
  end
end

app/views/sro/create.html.erb
<h1>Založenie spoločnosti</h1>
 
 <% if flash[:step1] == "invalid" %>
  <span class="error_box"><%= flash[:notice] %></span>
 <% end %>
 
   <div id="sidebar">
    <h3>Informácia:</h3>
    Údaje o navrhovateľovi sú automaticky načítané z profilu prihláseného používateľa, skontrolujte si ich.
  </div>
 
 <h3>Navrhovateľ</h3>
 <b>Titul pred menom:</b> <%= @navrh.t_pred %> <br/>
 <b>Meno:</b> <%= @navrh.meno %> <br/>
 <b>Priezvisko:</b> <%= @navrh.priez %> <br/>
 <b>Titul za menom:</b> <%= @navrh.t_za %> <br/>
 <b>Názov ulice:</b> <%= @navrh.ulica %> <br/>
 <b>Súpisné číslo:</b> <%= @navrh.cislo %> <br/>
 <b>Obec:</b> <%= @navrh.obec %> <br/>
 <b>PSČ:</b> <%= @navrh.psc %> <br/>
 <b>Štát:</b> <%= @navrh.stat %> <br/>
 
 <%= form_for(@sro, :url => {:controller => 'sro', :action => 'step12'}) do |sro| %>
  <h3> Názov:</h3>
  <%= sro.text_field :nazov, :size => 30 %>
  <h3>Sídlo</h3>
   <p> Ulica:<br/> <%= sro.text_field :ulica, :size => 50 %> </p>
   <p> Súpisné číslo:<br/> <%= sro.text_field :cislo, :size => 5 %> </p>
   <p> Obec:<br/> <%= sro.text_field :obec, :size => 30 %> </p>
   <p> PSČ:<br/> <%= sro.text_field :psc, :size => 5 %> </p>
   <p> Štát:<br/> <%= sro.text_field :stat, :size => 30 %> </p>
   <%= sro.hidden_field :proces, :value => "step2" %>
  <%= sro.submit :Pokračuj , :class => "btn-next"%>
 <% end %>
 
 <% if @sro.errors.any? %>
    <ul>
    <% for message_error in @sro.errors.full_messages %>
      <li style="color:red"><%= message_error %></li>
    <% end %>
    </ul>
 <% end %>
  

app/views/sro/show.html.erb
<h1>Spoločnosti</h1>

 <% if flash[:step1] == "valid" %>
  <span class="success_box"><%= flash[:notice] %></span>
 <% elsif flash[:step1] == "invalid" %>
  <span class="error_box"><%= flash[:notice] %></span>
 <% end %>

<h3>Moje spoločnosti</h3>
<% @sros.each do |sro| %>
  <p>
  <b><%= sro.nazov %></b>&nbsp;&nbsp;
  <% if sro.proces.eql? "step8" %>
      <%= link_to "Dokončené", :controller => "sro", :action => sro.proces, :sro_id => sro.id.to_s %>
  <% else %>
      <%= link_to "Pokračovať", :controller => "sro", :action => sro.proces, :sro_id => sro.id.to_s %>
  <% end %>
  |
  <%= link_to "Zmazať", sro_delete_path(:sro_id => sro.id), method: :delete,  data: { confirm: "Naozaj chete spoločnosť v procese vymazať?" } %>
  </p>
<% end %>
<hr/>
<%= link_to "Založiť s.r.o.", controller: "sro", action: "create" %>

app/views/sro/step2.html.erb
<h1>Činnosti</h1>

 <% if flash[:status] == "invalid" %>
  <p><span class="error_box"><%= flash[:notice] %></span></p>
 <% end %>

  <div id="sidebar">
    <h3>Informácia:</h3>
    <ul>
      <li>Podržaním tlačidla <b>ctrl</b> vyberiete viacero možností</li>
      <li>Vybrané činnosti budú overené v Živnostenskom registri pre vytváranú spoločnosť</li>
      <li>V prípade dodatočného pridania ďalších činností sa k tomuto kroku môžete kedykoľvek vrátiť a vybrať potrebnú činnosť</li>
    </ul>
  </div>

<% if params[:resps] %>
  <b>Spoločnosť podľa Živnostenského registra SR nemá oprávnenia na nasledovné činnosti:</b>
<ul>
  <% params[:resps].each do |r| %>
    <li><%= r %></li>
  <%  end %>
</ul>
<% end %>
<br/>
<%= form_for(@sro, :url => {:controller => 'sro', :action => 'step23'}) do |f| %>

  <%= fields_for(@group) do |cc| %>
    <%= f.collection_select( :operation_ids, @all_operations, :id, :popis, {}, { :multiple => true }) %>
  <% end %>
  <%= f.hidden_field :proces, :value => "step3" %>
  <%= f.hidden_field :id, :value => @sro.id %>
  <br/>
  <%= f.submit "Pokračovať",:class => "btn-next" %>
<% end %>

app/views/sro/step3.html.erb
<h1>Spoločníci</h1>

 <% if flash[:status] == "invalid" %>
  <span class="error_box"><%= flash[:notice] %></span>
 <% end %>

<h3>Pridaní</h3>
<div class = "list">
<%= render 'people/list' %>
</div>

<h3>Pridaj</h3>
<%= form_for @person, :remote => true do |f| %>
  <p> Titul/y pred menom:<br/> <%= f.text_field :t_pred, :size => 10 %> </p>
  <p> Meno:<br/> <%= f.text_field :meno%> </p>
  <p> Priezvisko:<br/> <%= f.text_field :priez%> </p>
  <p> Titul/y za menom:<br/> <%= f.text_field :t_za, :size => 10 %> </p>
  <p> Rodné číslo:<br/> <%= f.text_field :rc, :size => 20 %> </p>
  <h4>Adresa</h4>
  <p> Ulica:<br/> <%= f.text_field :ulica, :size => 50 %> </p>
  <p> Súpisné číslo:<br/> <%= f.text_field :cislo, :size => 5 %> </p>
  <p> Obec:<br/> <%= f.text_field :obec, :size => 30 %> </p>
  <p> PSČ:<br/> <%= f.text_field :psc, :size => 5 %> </p>
  <p> Štát:<br/> <%= f.text_field :stat, :size => 30 %> </p>
  <h4>Vklady</h4>
  <p> Vklad:<br/> <%= f.text_field :vklad, :size => 15 %> EUR </p>
  <p> Splatené:<br/> <%= f.text_field :splatene, :size => 15 %> EUR </p>
  <%= f.hidden_field :typ, :value => 1 %>
  <%= f.hidden_field :dat_nar, :value => "1" %>
  <%= f.hidden_field :sposob, :value => "a" %>
  <%= f.hidden_field :sro_id, :value => @sro.id %>
  <%= f.submit :Pridaj, :class => "btn-next" %>
<% end %>
<hr>
<%= link_to "Späť", sro_step2_path(:sro_id => @sro.id) , :style => "float:left" %>
 
<%=form_for(@sro, :url => {:controller => 'sro', :action => 'step34'}) do |f| %>
  <%= f.hidden_field :id, :value => @sro.id %>
  <%= f.submit "Pokračovať" , :style => "float:right",:class => "btn-next" %>
<% end %>

app/views/sro/step4.html.erb
<h1>Konatelia</h1>

<% if flash[:status] == "invalid" %>
  <span class="error_box"><%= flash[:notice] %></span>
<% end %>

<h3>Pridaní</h3>
<div class = "list">
<%= render 'people/list' %>
</div>

<h3>Pridaj</h3>
<%= form_for @person, :remote => true do |f| %>
  <p> Titul/y pred menom:<br/> <%= f.text_field :t_pred, :size => 10 %> </p>
  <p> Meno:<br/> <%= f.text_field :meno%> </p>
  <p> Priezvisko:<br/> <%= f.text_field :priez%> </p>
  <p> Titul/y za menom:<br/> <%= f.text_field :t_za, :size => 10 %> </p>
  <p> Dátum narodenia:<br/> <%= f.text_field :dat_nar, :size => 20 %> </p>
  <p> Rodné číslo:<br/> <%= f.text_field :rc, :size => 20 %> </p>
  <h4>Adresa</h4>
  <p> Ulica:<br/> <%= f.text_field :ulica, :size => 50 %> </p>
  <p> Súpisné číslo:<br/> <%= f.text_field :cislo, :size => 5 %> </p>
  <p> Obec:<br/> <%= f.text_field :obec, :size => 30 %> </p>
  <p> PSČ:<br/> <%= f.text_field :psc, :size => 5 %> </p>
  <p> Štát:<br/> <%= f.text_field :stat, :size => 30 %> </p>
  <h4>Spôsob konania štatutárneho orgánu v mene spoločnosti</h4>
  <%= f.text_area :sposob %> </p>
  <%= f.hidden_field :typ, :value => 2 %>
  <%= f.hidden_field :vklad, :value => "1" %>
  <%= f.hidden_field :splatene, :value => "1" %>
  <%= f.hidden_field :sro_id, :value => @sro.id %>
  <%= f.submit :Pridaj, :class => "btn-next" %>
<% end %>
<hr>
<%= link_to "Späť", sro_step3_path(:sro_id => @sro.id) , :style => "float:left" %>
 
<%= form_for(@sro, :url => {:controller => 'sro', :action => 'step45'}) do |f| %>
  <%= f.hidden_field :id, :value => @sro.id %>
  <%= f.submit "Pokračovať" ,:style => "float:right",:class => "btn-next" %>
<% end %>

app/views/sro/step5.html.erb
<h1>Dozorná rada</h1>

<% if flash[:status] == "invalid" %>
  <span class="error_box"><%= flash[:notice] %></span>
<% end %>

<h3>Pridaní členovia</h3>
<div class = "list">
<%= render 'people/list' %>
</div>

<h3>Pridaj člena</h3>
<%= form_for @person, :remote => true do |f| %>
  <p> Titul/y pred menom:<br/> <%= f.text_field :t_pred, :size => 10 %> </p>
  <p> Meno:<br/> <%= f.text_field :meno%> </p>
  <p> Priezvisko:<br/> <%= f.text_field :priez%> </p>
  <p> Titul/y za menom:<br/> <%= f.text_field :t_za, :size => 10 %> </p>
  <p> Dátum narodenia:<br/> <%= f.text_field :dat_nar, :size => 20 %> </p>
  <p> Rodné číslo:<br/> <%= f.text_field :rc, :size => 20 %> </p>
  <h4>Adresa</h4>
  <p> Ulica:<br/> <%= f.text_field :ulica, :size => 50 %> </p>
  <p> Súpisné číslo:<br/> <%= f.text_field :cislo, :size => 5 %> </p>
  <p> Obec:<br/> <%= f.text_field :obec, :size => 30 %> </p>
  <p> PSČ:<br/> <%= f.text_field :psc, :size => 5 %> </p>
  <p> Štát:<br/> <%= f.text_field :stat, :size => 30 %> </p>
  <%= f.hidden_field :typ, :value => 3 %>
  <%= f.hidden_field :sposob, :value => "a" %>
  <%= f.hidden_field :vklad, :value => "1" %>
  <%= f.hidden_field :splatene, :value => "1" %>
  <%= f.hidden_field :sro_id, :value => @sro.id %>
  <%= f.submit :Pridaj, :class => "btn-next" %>
<% end %>
<hr>
<%= link_to "Späť", sro_step4_path(:sro_id => @sro.id) , :style => "float:left" %>
 
<%= form_for(@sro, :url => {:controller => 'sro', :action => 'step56'}) do |f| %>
  <%= f.hidden_field :id, :value => @sro.id %>
  <%= f.submit "Pokračovať" , :style => "float:right", :class => "btn-next" %>
<% end %>

app/views/sro/step6.html.erb
<h1>Imanie</h1>

 <% if flash[:status] == "invalid" %>
  <span class="error_box"><%= flash[:notice] %></span>
 <% end %>
  <%if @sro.errors.any? %>
    <ul>
    <% for message_error in @sro.errors.full_messages %>
      <li style="color:red"><%= message_error %></li>
    <% end %>
    </ul>
 <% end %>

<%= form_for(@sro, :url => {:controller => 'sro', :action => 'step67'}) do |sro| %>
   <p>
    Základné imanie spoločnosti: <br/>
    <%= sro.text_field :imanie, :size => 10 %>
   </p>
   <p>
    Rozsah splatenia: <br/>
    <%= sro.text_field :splatene %>
   </p>
   <p>
    IBAN: <br/>
    <%= text_field :banka , :iban %>
   </p>
 
  <hr> 
  <%= link_to "Späť", sro_step5_path(:sro_id => @sro.id) , :style => "float:left" %>
  <%= sro.hidden_field :id, :value => @sro.id %>
  <%= sro.submit :Pokračuj , :style => "float:right" , :class => "btn-next" %>
 <% end %>

app/views/sro/step7.html.erb
<h1>Dokumenty</h1>

<% if flash[:status] == "invalid" %>
  <p><span class="error_box"><%= flash[:notice] %></span></p>
<% end %>

  <div id="sidebar">
    <h3>Informácia:</h3>
    Podporované formáty sú:
    <ul>
      <li>.zip</li>
      <li>.rar</li>
      <li>.tar</li>
      <li>.gz</li>
    </ul>
  </div>

Vložte skomprimovaný balík obsahujúci tieto overené dokumenty:
<ul>
  <li>Podpísaná spoločenská zmluva</li>
  <li>Podpisový vzor konateľov</li>
  <li>Nájomná zmluva alebo list vlastníctva pre sídlo s.r.o.</li>
</ul>

<%= form_for(:zip, :url => {:controller => 'sro', :action => 'step78'}, :html => { :multipart => true }) do |f|%>
  <p><%= f.file_field :file %></p>
  <%= fields_for @sro do |srof| %>
    <%= srof.hidden_field :id, :value => @sro.id %>
  <% end %>
  <hr>
  <%= link_to "Späť", sro_step6_path(:sro_id => @sro.id) , :style => "float:left" %>
  <%= token_tag form_authenticity_token %>
  <%= f.submit "Pokračovať" , :style => "float:right",:class => "btn-next" %>
<% end %>

app/views/sro/step8.html.erb
<h1>Dokončené</h1>
<p>
  <b>Uložené dokumenty:</b> <a href="<%= @zip.file.url %>" title="Dokumenty">stiahnuť</a><br/><br/>
  Pokiaľ ich chcete zmeniť, vrátte sa o krok späť a nahrajte nový balík.
</p>
<h3>Stav požiadavky:</h3>
<p style="border:1px black;box-shadow: 0px 0px 4px 1px;padding:2px"><b><%= print_status(@sro) %></b></p>
<h3>Dôležité</h3>
Po schválení a skontrolvaní údajov pracovníkom ORSR v príslušnom okresnom súde
podľa sídla spoločnosti vzniká spoločnosti povinnosť registrácie na Daňovom úrade SR
(môžete využiť opakovane tento portál) do <b>30</b> kalendárnych dní.
<hr>
<%= link_to "Späť", sro_step7_path(:sro_id => @sro.id) , :style => "float:left" %>